// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TTT.Database;

#nullable disable

namespace TTT.Migrations
{
    [DbContext(typeof(TttDbContext))]
    [Migration("20251110112644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TTT.TrainData.DataSets.CurrentTrainPosition", b =>
                {
                    b.Property<string>("TrainId")
                        .HasColumnType("text");

                    b.Property<string>("Direction")
                        .HasColumnType("text");

                    b.Property<string>("Line")
                        .HasColumnType("text");

                    b.Property<string>("LocStanox")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TrainId");

                    b.ToTable("CurrentPositions");
                });

            modelBuilder.Entity("TTT.TrainData.DataSets.Location", b =>
                {
                    b.Property<string>("Stanox")
                        .HasColumnType("text");

                    b.Property<string>("Crs")
                        .HasColumnType("text");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lon")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tiploc")
                        .HasColumnType("text");

                    b.HasKey("Stanox");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TTT.TrainData.DataSets.MovementEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActualTimestampMs")
                        .HasColumnType("bigint");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocStanox")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NextReportStanox")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<string>("TocId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrainId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VariationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TrainId", "ActualTimestampMs", "LocStanox", "EventType")
                        .IsUnique();

                    b.ToTable("MovementEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
